[package]
name = "first-rust-app"
version = "0.1.2"
edition = "2021"
description = "My app"

[dependencies]
actix-web = { version = "4.4.1", features = ["default"] }
mongodb = "2.7.1"
serde = "1.0.194"
ts-rs = "7.0"
tokio = { version = "1.35.1", features = ["full"] }
dotenv = "0.15.0"
