# syntax = denzp/cargo-wharf-frontend
[package]
name = "first-rust-app"
version = "0.1.2"
edition = "2021"
description = "My app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.2.1", features = ["default"] }
mongodb = "2.3.1"
serde = "1.0.151"
ts-rs = "6.2"
tokio = { version = "1.23.0", features = ["full"] }
dotenv = "0.15.0"

[package.metadata.wharf.builder]
image = "clux/muslrust:stable"
target = "x86_64-unknown-linux-musl"

[package.metadata.wharf.output]
image = "scratch"
workdir = "/"
entrypoint = ["/usr/local/bin/first-rust-app"]

[package.metadata.wharf.binary]
name = "first-rust-app"
description = "/usr/local/bin/first-rust-app"
