[package]
name = "first-rust-app"
version = "0.1.2"
edition = "2021"
description = "My app"

[profile.release]
opt-level = "z"
codegen-units = 1
strip = true
lto = true

[dependencies]
actix-web = { version = "4.5.1", features = ["default"] }
mongodb = "2.8"
serde = "1.0.200"
ts-rs = "9.0"
tokio = { version = "1.37", features = ["full"] }
dotenv = "0.15.0"
