[package]
name = "first-rust-app"
version = "0.1.2"
edition = "2021"
description = "My app"

[dependencies]
actix-web = { version = "4.4.0", features = ["default"] }
mongodb = "2.7.0"
serde = "1.0.188"
ts-rs = "6.2"
tokio = { version = "1.32.0", features = ["full"] }
dotenv = "0.15.0"
