[package]
name = "first-rust-app"
version = "0.1.2"
edition = "2021"
description = "My app"

[lib]
crate-type = ["cdylib"]

[dependencies]
spin-sdk = { version = "2.0", features = ["http-json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
http = "0.2"

# For HTTP requests to external services (like MongoDB Atlas)
spin-sdk = { version = "2.0", features = ["http-json", "key-value"] }