[package]
name = "first-rust-app"
version = "0.1.2"
edition = "2021"
description = "My app"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "4.1.0", features = ["default"] }
mongodb = "2.3.0"
serde = "1.0.144"
tokio = { version = "1.20.1", features = ["full"] }
