apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: a-team
  namespace: dbs
spec:
  instances: 2
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-credentials
  storage:
    size: 5Gi
    storageClass: standard
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: default
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: postgres-credentials

  storage:
    size: 5Gi
    storageClass: standard

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"


---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: app
  password: secure-password-123

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  selector:
    cnpg.io/cluster: postgres-cluster
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP