version: 2.1
#orbs:
#  rust: circleci/rust@1.6.0
caches:
  cargo: ~/.cargo
jobs:
  lint:
    docker:
      - image: cimg/rust:1.71.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ .Branch }}-{{ checksum "Cargo.lock" }}
      - run: cargo clippy
      - save_cache:
          key: cargo-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
  test:
    docker:
      - image: cimg/rust:1.71.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ .Branch }}-{{ checksum "Cargo.lock" }}
      - run: cargo test
      - save_cache:
          key: cargo-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
  build:
    docker:
      - image: cimg/rust:1.71.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-{{ .Branch }}-{{ checksum "Cargo.lock" }}
      - run: cargo build --release
      - save_cache:
          key: cargo-{{ .Branch }}-{{ checksum "Cargo.lock" }}
          paths:
            - ~/.cargo
  container:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker buildx build . -t yurikrupnik/kaniko-first-rust-app
workflows:
  build:
    jobs:
      - build
      - test
      - lint
      - container
