version: 2.1
orbs:
#  nx: nrwl/nx@1.5.1
#  go: circleci/go@1.7.3
#  pnpm-release-management: rkesters/pnpm-release-management@0.0.1
#  slack: circleci/slack@4.12.5
#  aws-cli: circleci/aws-cli@4.0.0
jobs:
  lint:
    docker:
      - image: cimg/rust:1.71.0
    steps:
      - checkout
      - run: cargo clippy
  test:
    docker:
      - image: cimg/rust:1.71.0
    steps:
      - checkout
      - run: cargo test
  build:
    docker:
      - image: cimg/rust:1.71.0
    steps:
      - checkout
      - run: cargo build --release
  container:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run: docker buildx build . -t yurikrupnik/kaniko-first-rust-app
workflows:
  build:
    jobs:
      - build
      - test
      - lint
      - container
