apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: first-rust-app
  namespace: aris
spec:
  interval: 5m0s
  dependsOn: []
  path: k8s/base
  prune: true
  targetNamespace: aris
  sourceRef:
    kind: GitRepository
    name: first-rust-app
    namespace: aris
