apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-rust-app
  namespace: default
  labels:
    app.kubernetes.io/name: first-rust-app
    app.kubernetes.io/version: ${VERSION:=latest}
    environment: ${ENVIRONMENT:=development}
spec:
  replicas: ${REPLICA_COUNT:=3}
  selector:
    matchLabels:
      app: first-rust-app
  template:
    metadata:
      labels:
        app: first-rust-app
        app.kubernetes.io/name: first-rust-app
        app.kubernetes.io/version: ${VERSION:=latest}
    spec:
      containers:
      - name: first-rust-app
        image: ghcr.io/yurikrupnik/first-rust-app:latest # {"$imagepolicy": "flux-system:first-rust-app"}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "postgres://app:secure-password-123@postgres-service:5432/app"
        - name: REDIS_URL
          value: "redis://redis-service:6379"
        - name: MONGODB_URL
          value: "mongodb://admin:password123@mongodb-service:27017"
        - name: JWT_SECRET
          value: "your-jwt-secret-key-change-this-in-production"
        - name: JWT_EXPIRES_IN
          value: "3600"
        - name: JWT_REFRESH_EXPIRES_IN
          value: "604800"
        - name: PORT
          value: "8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: first-rust-app
  namespace: default
  labels:
    app.kubernetes.io/name: first-rust-app
spec:
  selector:
    app: first-rust-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: first-rust-app
  namespace: default
  labels:
    app.kubernetes.io/name: first-rust-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - first-rust-app-${ENVIRONMENT:=dev}.local
      secretName: first-rust-app-tls
  rules:
  - host: first-rust-app-${ENVIRONMENT:=dev}.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: first-rust-app
            port:
              number: 8080