apiVersion: v1
kind: Namespace
metadata:
  name: a-team
---
apiVersion: v1
kind: Namespace
metadata:
  name: b-team
---
apiVersion: v1
kind: Namespace
metadata:
  name: innovation
---
apiVersion: v1
kind: Namespace
metadata:
  name: data
---
apiVersion: v1
kind: Namespace
metadata:
  name: aris
