name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Lint
        run: cargo clippy

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: rustup toolchain install stable --profile minimal
    - uses: Swatinem/rust-cache@v2
    - run: rustup target add x86_64-unknown-linux-musl
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl
    - run: ls target
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#      - uses: docker/metadata-action@v4
#        id: metadata
#        with:
#          images: ghcr.io/${{ github.repository }}
##          images: yurikrupnik/${{ github.repository }}
#          tags: |
#            type=ref,event=branch
#            type=ref,event=pr
#            type=semver,pattern={{version}}
#            type=semver,pattern={{major}}.{{minor}}
      - run: rustup show
#      - run: gcloud config list
#      - id: 'auth'
#        uses: 'google-github-actions/auth@v0'
#        with:
#          workload_identity_provider: 'projects/922939596495/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
#          service_account: 'container-builder-sa@mussia-infra.iam.gserviceaccount.com'
#      - name: 'Set up Cloud SDK'
#        uses: 'google-github-actions/setup-gcloud@v0'
#      - run: |-
#          gcloud --quiet auth configure-docker europe-central2-docker.pkg.dev
#      - name: Build Container
#        run: docker buildx build --platform=linux/amd64 --push --target final . -t yurikrupnik/first-rust-app
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: yurikrupnik/first-rust-app
  kaniko:
    runs-on: ubuntu-latest
#    permissions:
#      contents: 'read'
#      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log into registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#      - uses: docker/metadata-action@v4
#        id: metadata
#        with:
#          images: ghcr.io/${{ github.repository }}
#          #          images: yurikrupnik/${{ github.repository }}
#          tags: |
#            type=ref,event=branch
#            type=ref,event=pr
#            type=semver,pattern={{version}}
#            type=semver,pattern={{major}}.{{minor}}

      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: yurikrupnik/kaniko-first-rust-app
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          cache: true
#          cache_registry: syurikrupnik/kaniko-first-rust-app-cache